/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class Facturas extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Facturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgFacturas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_NuevaFactura = new javax.swing.JButton();
        btn_AdministrarFactura = new javax.swing.JButton();
        btn_EliminarFactura = new javax.swing.JButton();

        panel_BgFacturas.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Factura", "Id_Pedido", "Cliente", "Monto", "Estado", "Metodo_Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_NuevaFactura.setText("Nueva Factura");
        btn_NuevaFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_AdministrarFactura.setText("Administrar Factura");
        btn_AdministrarFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AdministrarFactura.addActionListener(this::btn_AdministrarFacturaActionPerformed);

        btn_EliminarFactura.setText("Eliminar Factura");
        btn_EliminarFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarFactura.addActionListener(this::btn_EliminarFacturaActionPerformed);

        javax.swing.GroupLayout panel_BgFacturasLayout = new javax.swing.GroupLayout(panel_BgFacturas);
        panel_BgFacturas.setLayout(panel_BgFacturasLayout);
        panel_BgFacturasLayout.setHorizontalGroup(
            panel_BgFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(panel_BgFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_NuevaFactura)
                .addGap(27, 27, 27)
                .addComponent(btn_AdministrarFactura)
                .addGap(36, 36, 36)
                .addComponent(btn_EliminarFactura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_BgFacturasLayout.setVerticalGroup(
            panel_BgFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgFacturasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_BgFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NuevaFactura)
                    .addComponent(btn_AdministrarFactura)
                    .addComponent(btn_EliminarFactura))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdministrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdministrarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AdministrarFacturaActionPerformed

    private void btn_EliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AdministrarFactura;
    private javax.swing.JButton btn_EliminarFactura;
    private javax.swing.JButton btn_NuevaFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_BgFacturas;
    // End of variables declaration//GEN-END:variables
}
