/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class GestionUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public GestionUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgGestion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Usuarios = new javax.swing.JTable();
        btn_CrearUsuario = new javax.swing.JButton();
        btn_BuscarUsuario = new javax.swing.JButton();
        btn_ModificarUsuario = new javax.swing.JButton();
        btn_EliminarUsuario = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(710, 470));

        panel_BgGestion.setBackground(new java.awt.Color(255, 255, 255));

        tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Puesto", "Usuario", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Usuarios.setPreferredSize(new java.awt.Dimension(710, 120));
        jScrollPane1.setViewportView(tabla_Usuarios);

        btn_CrearUsuario.setText("Crear Usuario");
        btn_CrearUsuario.addActionListener(this::btn_CrearUsuarioActionPerformed);

        btn_BuscarUsuario.setText("Buscar Usuario");

        btn_ModificarUsuario.setText("Modificar Usuario");
        btn_ModificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ModificarUsuario.addActionListener(this::btn_ModificarUsuarioActionPerformed);

        btn_EliminarUsuario.setText("Eliminar Usuario");
        btn_EliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarUsuario.addActionListener(this::btn_EliminarUsuarioActionPerformed);

        javax.swing.GroupLayout panel_BgGestionLayout = new javax.swing.GroupLayout(panel_BgGestion);
        panel_BgGestion.setLayout(panel_BgGestionLayout);
        panel_BgGestionLayout.setHorizontalGroup(
            panel_BgGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_BgGestionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_CrearUsuario)
                .addGap(27, 27, 27)
                .addComponent(btn_BuscarUsuario)
                .addGap(54, 54, 54)
                .addComponent(btn_ModificarUsuario)
                .addGap(32, 32, 32)
                .addComponent(btn_EliminarUsuario)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panel_BgGestionLayout.setVerticalGroup(
            panel_BgGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgGestionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_BgGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CrearUsuario)
                    .addComponent(btn_BuscarUsuario)
                    .addComponent(btn_ModificarUsuario)
                    .addComponent(btn_EliminarUsuario))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_BgGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CrearUsuarioActionPerformed

    private void btn_ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ModificarUsuarioActionPerformed

    private void btn_EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BuscarUsuario;
    private javax.swing.JButton btn_CrearUsuario;
    private javax.swing.JButton btn_EliminarUsuario;
    private javax.swing.JButton btn_ModificarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_BgGestion;
    private javax.swing.JTable tabla_Usuarios;
    // End of variables declaration//GEN-END:variables
}
