/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgInicio = new javax.swing.JPanel();
        panel_PerfumesTop = new javax.swing.JPanel();
        lbl_PerfumesTop = new javax.swing.JLabel();
        panel_StockBajo = new javax.swing.JPanel();
        lbl_StockBajo = new javax.swing.JLabel();
        panel_PedidosPendientes = new javax.swing.JPanel();
        lbl_PedidosPendientes = new javax.swing.JLabel();

        panel_BgInicio.setBackground(new java.awt.Color(255, 255, 255));

        panel_PerfumesTop.setBackground(new java.awt.Color(204, 204, 204));

        lbl_PerfumesTop.setText("Top Perfumes más Vendidos");

        javax.swing.GroupLayout panel_PerfumesTopLayout = new javax.swing.GroupLayout(panel_PerfumesTop);
        panel_PerfumesTop.setLayout(panel_PerfumesTopLayout);
        panel_PerfumesTopLayout.setHorizontalGroup(
            panel_PerfumesTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PerfumesTopLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_PerfumesTop)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panel_PerfumesTopLayout.setVerticalGroup(
            panel_PerfumesTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PerfumesTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_PerfumesTop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_StockBajo.setBackground(new java.awt.Color(204, 204, 204));

        lbl_StockBajo.setText("Alerta: Stock Bajo");

        javax.swing.GroupLayout panel_StockBajoLayout = new javax.swing.GroupLayout(panel_StockBajo);
        panel_StockBajo.setLayout(panel_StockBajoLayout);
        panel_StockBajoLayout.setHorizontalGroup(
            panel_StockBajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_StockBajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_StockBajoLayout.setVerticalGroup(
            panel_StockBajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_StockBajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_StockBajo)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        panel_PedidosPendientes.setBackground(new java.awt.Color(204, 204, 204));

        lbl_PedidosPendientes.setText("Pedidos Pendientes");

        javax.swing.GroupLayout panel_PedidosPendientesLayout = new javax.swing.GroupLayout(panel_PedidosPendientes);
        panel_PedidosPendientes.setLayout(panel_PedidosPendientesLayout);
        panel_PedidosPendientesLayout.setHorizontalGroup(
            panel_PedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PedidosPendientesLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lbl_PedidosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_PedidosPendientesLayout.setVerticalGroup(
            panel_PedidosPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PedidosPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_PedidosPendientes)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_BgInicioLayout = new javax.swing.GroupLayout(panel_BgInicio);
        panel_BgInicio.setLayout(panel_BgInicioLayout);
        panel_BgInicioLayout.setHorizontalGroup(
            panel_BgInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgInicioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panel_PerfumesTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(panel_BgInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_StockBajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_PedidosPendientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_BgInicioLayout.setVerticalGroup(
            panel_BgInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel_StockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(panel_PedidosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(panel_BgInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_PerfumesTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_PedidosPendientes;
    private javax.swing.JLabel lbl_PerfumesTop;
    private javax.swing.JLabel lbl_StockBajo;
    private javax.swing.JPanel panel_BgInicio;
    private javax.swing.JPanel panel_PedidosPendientes;
    private javax.swing.JPanel panel_PerfumesTop;
    private javax.swing.JPanel panel_StockBajo;
    // End of variables declaration//GEN-END:variables
}
