/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class ModuloDesarrollo extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public ModuloDesarrollo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgModuloD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Perfumes = new javax.swing.JTable();
        btn_NuevoPerfume = new javax.swing.JButton();
        btn_EditarPerfume = new javax.swing.JButton();
        btn_BuscarPerfume = new javax.swing.JButton();
        btn_BorrarPerfume = new javax.swing.JButton();
        btn_GestionarFormula = new javax.swing.JButton();

        panel_BgModuloD.setBackground(new java.awt.Color(255, 255, 255));

        tabla_Perfumes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Familia Olfativa", "Tipo", "Perfumista", "Costo Prod", "Costo Venta", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Perfumes);

        btn_NuevoPerfume.setText("Nuevo Perfume");
        btn_NuevoPerfume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_EditarPerfume.setText("Editar Perfume");
        btn_EditarPerfume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_BuscarPerfume.setText("Buscar Perfume");
        btn_BuscarPerfume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_BorrarPerfume.setText("Borrar Perfume");
        btn_BorrarPerfume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BorrarPerfume.addActionListener(this::btn_BorrarPerfumeActionPerformed);

        btn_GestionarFormula.setText("Gestionar Formula");
        btn_GestionarFormula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GestionarFormula.addActionListener(this::btn_GestionarFormulaActionPerformed);

        javax.swing.GroupLayout panel_BgModuloDLayout = new javax.swing.GroupLayout(panel_BgModuloD);
        panel_BgModuloD.setLayout(panel_BgModuloDLayout);
        panel_BgModuloDLayout.setHorizontalGroup(
            panel_BgModuloDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panel_BgModuloDLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_NuevoPerfume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EditarPerfume)
                .addGap(18, 18, 18)
                .addComponent(btn_BuscarPerfume)
                .addGap(18, 18, 18)
                .addComponent(btn_BorrarPerfume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_GestionarFormula)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panel_BgModuloDLayout.setVerticalGroup(
            panel_BgModuloDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgModuloDLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_BgModuloDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NuevoPerfume)
                    .addComponent(btn_BuscarPerfume)
                    .addComponent(btn_BorrarPerfume)
                    .addComponent(btn_GestionarFormula)
                    .addComponent(btn_EditarPerfume))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgModuloD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgModuloD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BorrarPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BorrarPerfumeActionPerformed

    private void btn_GestionarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GestionarFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GestionarFormulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BorrarPerfume;
    private javax.swing.JButton btn_BuscarPerfume;
    private javax.swing.JButton btn_EditarPerfume;
    private javax.swing.JButton btn_GestionarFormula;
    private javax.swing.JButton btn_NuevoPerfume;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_BgModuloD;
    private javax.swing.JTable tabla_Perfumes;
    // End of variables declaration//GEN-END:variables
}
