/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class Produccion extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Produccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgProduccion = new javax.swing.JPanel();
        lbl_Lotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_IniciarProduccion = new javax.swing.JButton();
        btn_FinalizarLote = new javax.swing.JButton();
        btn_EvaluarCalidad = new javax.swing.JButton();

        panel_BgProduccion.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Lotes.setText("Historial de Lotes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_Lote", "Perfume", "Cantidad", "Fecha_Inicio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_IniciarProduccion.setText("Iniciar Producción");
        btn_IniciarProduccion.addActionListener(this::btn_IniciarProduccionActionPerformed);

        btn_FinalizarLote.setText("Finalizar Lote");

        btn_EvaluarCalidad.setText("Evaluar Lote");
        btn_EvaluarCalidad.addActionListener(this::btn_EvaluarCalidadActionPerformed);

        javax.swing.GroupLayout panel_BgProduccionLayout = new javax.swing.GroupLayout(panel_BgProduccion);
        panel_BgProduccion.setLayout(panel_BgProduccionLayout);
        panel_BgProduccionLayout.setHorizontalGroup(
            panel_BgProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_BgProduccionLayout.createSequentialGroup()
                .addGroup(panel_BgProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_BgProduccionLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lbl_Lotes))
                    .addGroup(panel_BgProduccionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_IniciarProduccion)
                        .addGap(63, 63, 63)
                        .addComponent(btn_FinalizarLote)
                        .addGap(70, 70, 70)
                        .addComponent(btn_EvaluarCalidad)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panel_BgProduccionLayout.setVerticalGroup(
            panel_BgProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BgProduccionLayout.createSequentialGroup()
                .addComponent(lbl_Lotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panel_BgProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_IniciarProduccion)
                    .addComponent(btn_FinalizarLote)
                    .addComponent(btn_EvaluarCalidad))
                .addGap(0, 101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarProduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IniciarProduccionActionPerformed

    private void btn_EvaluarCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EvaluarCalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EvaluarCalidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EvaluarCalidad;
    private javax.swing.JButton btn_FinalizarLote;
    private javax.swing.JButton btn_IniciarProduccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Lotes;
    private javax.swing.JPanel panel_BgProduccion;
    // End of variables declaration//GEN-END:variables
}
