/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author herna
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_BgInicio = new javax.swing.JPanel();
        TP_Ventas = new javax.swing.JTabbedPane();
        panel_TPClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Clientes = new javax.swing.JTable();
        btn_GuardarCliente = new javax.swing.JButton();
        btn_ModificarCliente = new javax.swing.JButton();
        btn_BuscarCliente = new javax.swing.JButton();
        btn_EliminarCliente = new javax.swing.JButton();
        panel_TPPedidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Pedidos = new javax.swing.JTable();
        btn_NuevoPedido = new javax.swing.JButton();
        btn_AdministrarPedido = new javax.swing.JButton();
        btn_EliminarPedido = new javax.swing.JButton();

        panel_BgInicio.setBackground(new java.awt.Color(255, 255, 255));

        tabla_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Cliente", "Nombre", "RFC", "Tipo", "Dirección", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Clientes);

        btn_GuardarCliente.setText("Guardar Cliente");
        btn_GuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_GuardarCliente.addActionListener(this::btn_GuardarClienteActionPerformed);

        btn_ModificarCliente.setText("Modificar Cliente");
        btn_ModificarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_BuscarCliente.setText("Buscar");
        btn_BuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BuscarCliente.addActionListener(this::btn_BuscarClienteActionPerformed);

        btn_EliminarCliente.setText("Eliminar Cliente");
        btn_EliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_EliminarCliente.addActionListener(this::btn_EliminarClienteActionPerformed);

        javax.swing.GroupLayout panel_TPClientesLayout = new javax.swing.GroupLayout(panel_TPClientes);
        panel_TPClientes.setLayout(panel_TPClientesLayout);
        panel_TPClientesLayout.setHorizontalGroup(
            panel_TPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_TPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_GuardarCliente)
                .addGap(18, 18, 18)
                .addComponent(btn_ModificarCliente)
                .addGap(18, 18, 18)
                .addComponent(btn_BuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_EliminarCliente)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panel_TPClientesLayout.setVerticalGroup(
            panel_TPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_TPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GuardarCliente)
                    .addComponent(btn_ModificarCliente)
                    .addComponent(btn_BuscarCliente)
                    .addComponent(btn_EliminarCliente))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        TP_Ventas.addTab("Clientes", panel_TPClientes);

        tabla_Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id_Pedido", "Cliente", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_Pedidos);

        btn_NuevoPedido.setText("Nuevo Pedido");
        btn_NuevoPedido.addActionListener(this::btn_NuevoPedidoActionPerformed);

        btn_AdministrarPedido.setText("Administrar Pedido");

        btn_EliminarPedido.setText("Eliminar Pedido");

        javax.swing.GroupLayout panel_TPPedidosLayout = new javax.swing.GroupLayout(panel_TPPedidos);
        panel_TPPedidos.setLayout(panel_TPPedidosLayout);
        panel_TPPedidosLayout.setHorizontalGroup(
            panel_TPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(panel_TPPedidosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_NuevoPedido)
                .addGap(116, 116, 116)
                .addComponent(btn_AdministrarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btn_EliminarPedido)
                .addGap(102, 102, 102))
        );
        panel_TPPedidosLayout.setVerticalGroup(
            panel_TPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TPPedidosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_TPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NuevoPedido)
                    .addComponent(btn_AdministrarPedido)
                    .addComponent(btn_EliminarPedido))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        TP_Ventas.addTab("Pedidos", panel_TPPedidos);

        javax.swing.GroupLayout panel_BgInicioLayout = new javax.swing.GroupLayout(panel_BgInicio);
        panel_BgInicio.setLayout(panel_BgInicioLayout);
        panel_BgInicioLayout.setHorizontalGroup(
            panel_BgInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Ventas)
        );
        panel_BgInicioLayout.setVerticalGroup(
            panel_BgInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Ventas)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_BgInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GuardarClienteActionPerformed

    private void btn_BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarClienteActionPerformed

    private void btn_EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarClienteActionPerformed

    private void btn_NuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NuevoPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TP_Ventas;
    private javax.swing.JButton btn_AdministrarPedido;
    private javax.swing.JButton btn_BuscarCliente;
    private javax.swing.JButton btn_EliminarCliente;
    private javax.swing.JButton btn_EliminarPedido;
    private javax.swing.JButton btn_GuardarCliente;
    private javax.swing.JButton btn_ModificarCliente;
    private javax.swing.JButton btn_NuevoPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_BgInicio;
    private javax.swing.JPanel panel_TPClientes;
    private javax.swing.JPanel panel_TPPedidos;
    private javax.swing.JTable tabla_Clientes;
    private javax.swing.JTable tabla_Pedidos;
    // End of variables declaration//GEN-END:variables
}
